### ISSUE TITLE
MSVS 2019 Compatibility

### ISSUE THREAD

**Issue by spidermonkey1187** [Idered/vscode-extension-figma#3]
I am running MSVS 2019 Community.  I attempted to run your installer but it fails.  It apparently was made for MSVS 2017.  Do you have plans to implement 2019 support?  I have a project in MSVS which I am hoping to utilize with some FIGMA content.  

The install log is attached

[dd_VSIXInstaller_20190814160636_0a8c.log](https://github.com/Idered/vscode-extension-figma/files/3503676/dd_VSIXInstaller_20190814160636_0a8c.log)

**Comment by Idered** [comment]
Hey, this was made for visual studio code, I haven't tested it with visual studio. I don't have any plans to support visual studio, at least for now

**Comment by spidermonkey1187** [comment]
Ah I did not know that, now don't I feel silly, I can say this functionality is highly desirable in MSVS if you do end up getting around to it.
